name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  TZ: UTC
  PHP_VERSION: 7.3
  NODE_VERSION: 12.x

jobs:
  php:
    runs-on: ubuntu-latest
    name: php / ${{ matrix.test.name }}
    strategy:
      fail-fast: false
      matrix:
        test:
          - name: Lint Symfony's templates files
            script: bin/console lint:twig templates/

          - name: Lint Symfony's config files
            script: bin/console lint:yaml config/ --parse-tags

          - name: Lint Symfony's translations files
            script: bin/console lint:xliff translations

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none
          extensions: ctype, iconv, intl

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: $(composer config cache-files-dir)
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Run PHP Linting Tests
        run: "${{ matrix.test.script }}"
        continue-on-error: true  # Continuer en cas d'erreurs de lint

  javascript:
    runs-on: ubuntu-latest
    name: javascript / ${{ matrix.test.name }}
    strategy:
      fail-fast: false
      matrix:
        test:
          - name: Building for development
            script: yarn dev

          - name: Building for production
            script: yarn build

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: $(yarn cache dir)
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - run: yarn install --frozen-lockfile
